=== garrettvuky/Phase2_SWE_Testing/cases/schema/case.schema.json
{
  "$id": "https://phase2.local/schemas/case.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "additionalProperties": false,
  "properties": {
    "base_commit": {
      "minLength": 1,
      "type": "string"
    },
    "build_commands": {
      "items": {
        "minLength": 1,
        "type": "string"
      },
      "minItems": 1,
      "type": "array"
    },
    "case_id": {
      "minLength": 1,
      "type": "string"
    },
    "focal_file_path": {
      "minLength": 1,
      "type": "string"
    },
    "mapped_focal_method": {
      "minLength": 1,
      "type": "string"
    },
    "mapped_test_method": {
      "minLength": 1,
      "type": "string"
    },
    "metadata": {
      "type": "object"
    },
    "modified_commit": {
      "minLength": 1,
      "type": "string"
    },
    "repo_id": {
      "minLength": 1,
      "type": "string"
    },
    "test_file_path": {
      "minLength": 1,
      "type": "string"
    }
  },
  "required": [
    "case_id",
    "repo_id",
    "base_commit",
    "modified_commit",
    "focal_file_path",
    "test_file_path",
    "mapped_focal_method",
    "mapped_test_method",
    "build_commands"
  ],
  "title": "Phase2ChangeCase",
  "type": "object"
}

=== garrettvuky/Phase2_SWE_Testing/cases/case_3d175f545e032447/case.json
{
  "base_commit": "b3f2ee3d61f3276c843597d2e272a30f49d39ed0",
  "build_commands": [
    "mvn -B test"
  ],
  "case_id": "case_3d175f545e032447",
  "focal_file_path": "simple/src/main/java/org/apache/commons/rdf/simple/Types.java",
  "mapped_focal_method": "ntriplesString",
  "mapped_test_method": "testNtriplesString",
  "metadata": {
    "baseline_test_result_path": "C:\\Users\\osart\\OneDrive - Umich\\SWTProject\\Phase2_SWE_Testing\\phase2\\artifacts\\logs\\test_runs\\20260306T040910Z_20555659_test_run.json",
    "baseline_test_status": "error",
    "candidate_test_result_path": "C:\\Users\\osart\\OneDrive - Umich\\SWTProject\\Phase2_SWE_Testing\\phase2\\artifacts\\logs\\test_runs\\20260306T040913Z_20555659_test_run.json",
    "candidate_test_status": "error",
    "failures_appear": false,
    "human_update_commit": "18d39818c134d6c2de417c9a845383c3be99767c",
    "human_update_distance": 0,
    "human_update_found": true,
    "rank": 1,
    "record_id": "c2t_016a143a602dd7a494d2",
    "score": 3.0,
    "touches_method_region": false
  },
  "modified_commit": "18d39818c134d6c2de417c9a845383c3be99767c",
  "repo_id": "20555659",
  "test_file_path": "simple/src/test/java/org/apache/commons/rdf/simple/TypesTest.java"
}

=== garrettvuky/Phase2_SWE_Testing/cases/case_4da6ca3850986d5b/case.json
{
  "base_commit": "e6e574d2fd88a288cf84675c65b840cc35cf8564",
  "build_commands": [
    "mvn -B test"
  ],
  "case_id": "case_4da6ca3850986d5b",
  "focal_file_path": "sslr-core/src/main/java/org/sonar/sslr/internal/vm/lexerful/AdjacentExpression.java",
  "mapped_focal_method": "execute",
  "mapped_test_method": "should_backtrack3",
  "metadata": {
    "baseline_test_result_path": "C:\\Users\\osart\\OneDrive - Umich\\SWTProject\\Phase2_SWE_Testing\\phase2\\artifacts\\logs\\test_runs\\20260306T031750Z_4159017_test_run.json",
    "baseline_test_status": "error",
    "candidate_test_result_path": "C:\\Users\\osart\\OneDrive - Umich\\SWTProject\\Phase2_SWE_Testing\\phase2\\artifacts\\logs\\test_runs\\20260306T031757Z_4159017_test_run.json",
    "candidate_test_status": "error",
    "failures_appear": false,
    "human_update_commit": "19e68665097b5c1bfe861763b1bdbaa83b1b60f9",
    "human_update_distance": 0,
    "human_update_found": true,
    "rank": 1,
    "record_id": "c2t_05773544a25386642572",
    "score": 3.0,
    "touches_method_region": false
  },
  "modified_commit": "19e68665097b5c1bfe861763b1bdbaa83b1b60f9",
  "repo_id": "4159017",
  "test_file_path": "sslr-core/src/test/java/org/sonar/sslr/internal/vm/lexerful/AdjacentExpressionTest.java"
}

=== garrettvuky/Phase2_SWE_Testing/cases/case_9ad6abf00e0b446d/case.json
{
  "base_commit": "a5b4326a735dd3ed41b73f578edcb2cf45a243f6",
  "build_commands": [
    "'C:\\Users\\osart\\OneDrive - Umich\\SWTProject\\Phase2_SWE_Testing\\repos\\23257998\\gradlew.bat' test --console=plain"
  ],
  "case_id": "case_9ad6abf00e0b446d",
  "focal_file_path": "semdroid-core/src/main/java/com/oprisnik/semdroid/filter/BasicTypesLocalVarFilter.java",
  "mapped_focal_method": "use",
  "mapped_test_method": "testBasicTypesFilter",
  "metadata": {
    "baseline_test_result_path": "C:\\Users\\osart\\OneDrive - Umich\\SWTProject\\Phase2_SWE_Testing\\phase2\\artifacts\\logs\\test_runs\\20260306T041033Z_23257998_test_run.json",
    "baseline_test_status": "fail",
    "candidate_test_result_path": "C:\\Users\\osart\\OneDrive - Umich\\SWTProject\\Phase2_SWE_Testing\\phase2\\artifacts\\logs\\test_runs\\20260306T041043Z_23257998_test_run.json",
    "candidate_test_status": "fail",
    "failures_appear": false,
    "human_update_commit": null,
    "human_update_distance": null,
    "human_update_found": false,
    "rank": 1,
    "record_id": "c2t_2092379fc334190fec64",
    "score": 1.0,
    "touches_method_region": false
  },
  "modified_commit": "0ef0c26f756293492a8adf74fd66867800a0a0f3",
  "repo_id": "23257998",
  "test_file_path": "semdroid-core/src/test/java/com/oprisnik/semdroid/filter/BasicTypesLocalVarFilterTest.java"
}

=== garrettvuky/Phase2_SWE_Testing/cases/case_98657e7509ae2b67/case.json
{
  "base_commit": "e6e574d2fd88a288cf84675c65b840cc35cf8564",
  "build_commands": [
    "mvn -B test"
  ],
  "case_id": "case_98657e7509ae2b67",
  "focal_file_path": "sslr-core/src/main/java/com/sonar/sslr/api/typed/ActionParser.java",
  "mapped_focal_method": "parse",
  "mapped_test_method": "unknown_file",
  "metadata": {
    "baseline_test_result_path": "C:\\Users\\osart\\OneDrive - Umich\\SWTProject\\Phase2_SWE_Testing\\phase2\\artifacts\\logs\\test_runs\\20260306T031619Z_4159017_test_run.json",
    "baseline_test_status": "error",
    "candidate_test_result_path": "C:\\Users\\osart\\OneDrive - Umich\\SWTProject\\Phase2_SWE_Testing\\phase2\\artifacts\\logs\\test_runs\\20260306T031633Z_4159017_test_run.json",
    "candidate_test_status": "error",
    "failures_appear": false,
    "human_update_commit": "a0916c96e1be9ae9560e0275699cfbc9939a9090",
    "human_update_distance": 0,
    "human_update_found": true,
    "rank": 1,
    "record_id": "c2t_02e1fc2854da3da2c6f7",
    "score": 5.0,
    "touches_method_region": true
  },
  "modified_commit": "a0916c96e1be9ae9560e0275699cfbc9939a9090",
  "repo_id": "4159017",
  "test_file_path": "sslr-core/src/test/java/com/sonar/sslr/api/typed/ActionParserTest.java"
}

=== garrettvuky/Phase2_SWE_Testing/cases/case_2bc050c0f4890b10/case.json
{
  "base_commit": "3a9db9b04ae7d9545301ade8340ebd3b6baea138",
  "build_commands": [
    "'C:\\Users\\osart\\OneDrive - Umich\\SWTProject\\Phase2_SWE_Testing\\repos\\35897457\\gradlew.bat' test --console=plain"
  ],
  "case_id": "case_2bc050c0f4890b10",
  "focal_file_path": "nxparser-utilities-nx/src/main/java/org/semanticweb/yars/nx/NodeArrayComparator.java",
  "mapped_focal_method": "compare",
  "mapped_test_method": "test",
  "metadata": {
    "baseline_test_result_path": "C:\\Users\\osart\\OneDrive - Umich\\SWTProject\\Phase2_SWE_Testing\\phase2\\artifacts\\logs\\test_runs\\20260306T041248Z_35897457_test_run.json",
    "baseline_test_status": "fail",
    "candidate_test_result_path": "C:\\Users\\osart\\OneDrive - Umich\\SWTProject\\Phase2_SWE_Testing\\phase2\\artifacts\\logs\\test_runs\\20260306T041317Z_35897457_test_run.json",
    "candidate_test_status": "error",
    "failures_appear": false,
    "human_update_commit": "41a315a0d43ecbedd97898c001fe7bff48d81312",
    "human_update_distance": 0,
    "human_update_found": true,
    "rank": 1,
    "record_id": "c2t_386dff7fa05f6910842c",
    "score": 5.0,
    "touches_method_region": true
  },
  "modified_commit": "41a315a0d43ecbedd97898c001fe7bff48d81312",
  "repo_id": "35897457",
  "test_file_path": "nxparser-utilities-nx/src/test/java/org/semanticweb/yars/nx/NodeArrayComparatorTest.java"
}

=== garrettvuky/Phase2_SWE_Testing/cases/case_362b2cdc1406b24a/case.json
{
  "base_commit": "e6e574d2fd88a288cf84675c65b840cc35cf8564",
  "build_commands": [
    "mvn -B test"
  ],
  "case_id": "case_362b2cdc1406b24a",
  "focal_file_path": "sslr-core/src/main/java/com/sonar/sslr/api/typed/Optional.java",
  "mapped_focal_method": "or",
  "mapped_test_method": "absent_or_null",
  "metadata": {
    "baseline_test_result_path": "C:\\Users\\osart\\OneDrive - Umich\\SWTProject\\Phase2_SWE_Testing\\phase2\\artifacts\\logs\\test_runs\\20260306T031924Z_4159017_test_run.json",
    "baseline_test_status": "error",
    "candidate_test_result_path": "C:\\Users\\osart\\OneDrive - Umich\\SWTProject\\Phase2_SWE_Testing\\phase2\\artifacts\\logs\\test_runs\\20260306T031932Z_4159017_test_run.json",
    "candidate_test_status": "error",
    "failures_appear": false,
    "human_update_commit": "19e68665097b5c1bfe861763b1bdbaa83b1b60f9",
    "human_update_distance": 0,
    "human_update_found": true,
    "rank": 1,
    "record_id": "c2t_06aa942f9a28e24ddfeb",
    "score": 3.0,
    "touches_method_region": false
  },
  "modified_commit": "19e68665097b5c1bfe861763b1bdbaa83b1b60f9",
  "repo_id": "4159017",
  "test_file_path": "sslr-core/src/test/java/com/sonar/sslr/api/typed/OptionalTest.java"
}
